name:                microsmos
version:             0.0.0.0
github:              "NorfairKing/microsmos"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2019 Tom Sydney Kerckhove"

description:         Please see the README on GitHub at <https://github.com/NorfairKing/microsmos#readme>


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - brick
  - bytestring
  - containers
  - cursor
  - directory
  - path-io
  - text
  - vty
  - yaml

executables:
  microsmos:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - microsmos
